### PR TITLE
Implements request for vault-rs

### PR DESCRIPTION
**Pull request by ChrisMacNaughton**

### CODE REVIEW

**Comment by compressed** [comment]
@ChrisMacNaughton saw your commit pain earlier :/ I think I tracked this down to this issue: https://github.com/travis-ci/travis-ci/issues/7131

We need to add `dist: trusty` to the `.travis.yml`.

**Comment by ChrisMacNaughton** [comment]
Thanks for digging that up!

**Comment by cholcombe973** [comment]
woot!

**Comment by ChrisMacNaughton** [comment]
Can anybody using this try this branch to ensure that it works? I'm nervous about ripping apart the lower levels of this without additional confirmation :)

**Comment by compressed** [comment]
I would like to, but I'm also using some crates that haven't yet updated. Hopefully those will be getting upgraded within the next week or two also.

**Comment by compressed** [comment]
Oh also, we can probably update the chrono dependency to `0.3`. Could be done as a separate PR.

**Comment by ChrisMacNaughton** [comment]
I don't mind bumping a dependency in here :)

**Comment by cholcombe973** [comment]
I'll try and give this a spin today and see what happens

**Pull request merged**
