### PR TITLE
Improve testing with Vault versions

### PR DESCRIPTION
**Pull request by ChrisMacNaughton**

### CODE REVIEW

**Comment by ChrisMacNaughton** [comment]
@cholcombe973 @rokadias Thoughts on this change? There's a bit of API change because the types seem to be Optional before 1.2 but I'd prefer to have support as widely as possible

**Comment by rokadias** [comment]
Looks good to me.

I think it's reasonable to alter the versions as breaking changes are introduced from Vault. So I'm :+1: here.

**Comment by ChrisMacNaughton** [comment]
I'll work this into a release soon-ish, but may end up working on more test stuff in the meantime before the release

**Comment by rokadias** [comment]
Thanks for the update! Please let me know when you do so I can remove the exception in our `cargo audit`.

**Pull request merged**
