### PR TITLE
Duration

### PR DESCRIPTION
**Pull request by cholcombe973**
This is great work and i'd love to see it merged back in :)

### CODE REVIEW

**Comment by ChrisMacNaughton** [comment]
@compressed Got this stuff in, if you'd like, I'd be happy to throw your name into the authors: field for this crate!

**Comment by compressed** [comment]
@ChrisMacNaughton thanks for merging! Sorry I was away for a bit, didn't realize someone had opened up a PR for this :) I haven't updated the test cases for this functionality yet, but hopefully the code is correct.

Sure, that would be great if you could add me to the authors list.

I'm working on a project that uses vault, so I may make some more PRs depending on what else I need :)

 -- Chris

**Comment by ChrisMacNaughton** [comment]
@compressed would you like to be in as compressed, or by name? If by name, what name :)

**Comment by compressed** [comment]
Oops :), as this:

```
"Christopher Brickley <brickley@gmail.com>"
```

**Pull request merged**
