### PR TITLE
Permit passing a reqwest::blocking::Client to init

### PR DESCRIPTION
**Pull request by sempervictus**
There are numerous uses for Vaults in private environments which
are not well suited to the default reqwest::blocking::Client setup.
Self-signed certs, peer-certificate and client auth scenarios, or
simply execution from a place that has no CAs yet (initramfs) may
all require pre-constructing the HTTP client and passing it into
the Vault client after construction.

Implement new_from_reqwest for VaultClient<TokenData> to take a
third parameter of a pre-defined reqwest::blocking::Client in order
to interact with custom Vault setups or from constrained client
environments.

### CODE REVIEW

**Comment by sempervictus** [comment]
@ChrisMacNaughton: this is to permit MaaS to encrypt OS drives (working with someone from your side of the house on it) - the key-fetcher needs to run from initramfs, and the MaaS-hosted Vault might be self-signed (or require client-keys embedded), so need to be able to construct custom Reqwest clients for the job.

**Comment by ChrisMacNaughton** [comment]
Haven't looked at the code itself much yet, but this strongly conflicts with https://github.com/ChrisMacNaughton/vault-rs/issues/50 , and the reason I want to evaluate ureq is to reduce the dependency requirements on Vault-rs. As a consumer of these bindings, I'm curious about thoughts on the current dependency chain via Reqwest?

Additionally, I'm beginning to think that the VaultClient needs to implement a builder pattern to create one, as the complexity in the VaultClient is getting bigger.

**Comment by sempervictus** [comment]
Agree with your thoughts for a few reasons:
1. i dont want to carry a static openssl binary
2. the client construction should be more flexible for the reasons i listed
3. the actual need right now comes from [this](https://github.com/sempervictus/initunlock-rs/blob/main/src/main.rs#L45)

Would it be possible to merge this non-breaking change at the current minor version, and implement divorce from reqwest with a builder pattern for the next most significant release?

**Comment by ChrisMacNaughton** [comment]
As there's already a (single :-?) public method exposing Reqwest today, I'm OK merging this, and also want to focus soon on a 3.0 of the library that includes a builder and new http library.

**Comment by sempervictus** [comment]
Thank you sir - i'll update `Cargo.toml` in the initramfs decryptor to the next version of this crate once its up.

**Comment by ChrisMacNaughton** [comment]
Should be released as a minor version update :-)

**Comment by petermetz** [comment]
@ChrisMacNaughton I'm late for the party, but wanted to respond to this anyway:

> I'm curious about thoughts on the current dependency chain via Reqwest?

Reqwest is preventing me from building for wasm so if ureq would solve that I'd be a fan of the swap for sure.

I did a rudimentary test where I pulled in ureq as a crate in my Cargo.toml and wasm-pack did not complain (e.g. build successful)
```toml
ureq = { version = "2.2.0", features = ["json", "charset"] }
```

Build errors for Reqwest:

```sh
error[E0432]: unresolved import `reqwest::blocking`
  --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/hashicorp_vault-2.1.0/src/client/mod.rs:12:5
   |
12 |     blocking::{Client, Response},
   |     ^^^^^^^^ could not find `blocking` in `reqwest`

error[E0433]: failed to resolve: could not find `blocking` in `reqwest`
  --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/hashicorp_vault-2.1.0/src/client/error.rs:29:55
   |
29 |         VaultResponse(err: String, response: reqwest::blocking::Response) {
   |                                                       ^^^^^^^^ could not find `blocking` in `reqwest`

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `hashicorp_vault` due to 2 previous errors
Error: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit status: 101
  full command: "cargo" "build" "--lib" "--release" "--target" "wasm32-unknown-unknown"
```

**Pull request merged**
