### PR TITLE
AppRole support.. among others

### PR DESCRIPTION
**Pull request by compressed**
Here's some more work of mine. I've been trying to add `AppRole` backend support, among other things. Sorry for the large PR... I can split it up if it's easier.

Summary of the changes:
- Added `AppRole` backend.
- Added an "escape hatch" `call_endpoint` function. You can see how it works in the AppRole test case. I'm not sure how we can easily support all the different vault API methods, so I tried to write something more generic that would work for ANY endpoint. I'd imagine our API would have functions for the more common things that vault provides and then you could drop down the `endpoint_call` fn if it's not supported, this would help support the use case mentioned in #7. Note, I didn't implement the `LIST` http verb, since I didn't test it / have a use case for it. Open to feedback here.
- Added a CHANGELOG, similar to vault. Thought it may be a good idea. I was just checking their 0.6.2 release notes and they have more breaking changes already for AppRole (although we weren't impacted), but they've already deprecated `cubbyhole/response` so I needed to fix that as well. It would be good for users of the library to know what the breaking changes are in this one as well.
- Used constants where appropriate in the test cases.
- A fix for `WrapInfo::wrapped_accessor`; I didn't read the vault go code carefully enough before, this an optional field. 
- Mentioned `AppId` backend is deprecated.

One big question though, as evidenced by travis failures...
- How do we want to handle vault breaking changes? In 0.6.1, `request_id` field was added to all `VaultResponse`s. How do we want to handle that for testing in travis and in general for library users? It's a required field in 0.6.1, but is missing in all below versions. We could add feature flags as discussed in #6, but I worry that will become a maintenance burden as more breaking changes come in from vault. For example, with `request_id`, we'd need to make two different versions of the `VaultResponse` struct, one with a flag for `gte_vault_0.6.1` and one for `lt_vault_0.6.1`. I feel like things like this would get messy. Maybe we could just have a table and list which vault versions are known to work with which `vault-rs` versions?

### CODE REVIEW

**Comment by ChrisMacNaughton** [comment]
I like the look of this but it looks like it breaks all of the older versions of Vault

**Comment by ChrisMacNaughton** [comment]
Considering this a bit more, I'm thinking about calling a new version here and removing older than 0.6 here. Given that both we and Vault are not yet 1.0, I'm not too hurt by breaking it here. I may just cut a branch here and then merge in. Any thoughts @compressed @emk ?

**Comment by emk** [comment]
Yeah, 0.6 has been out for a while. In reality, I only care about two
versions of vault:
- What we run internally, which usually isn't too old. But we do lag a
  little behind, because we have a Redis-based HA backend that we maintain as
  a fork.
- The latest public release, for people downloading and trying cage for the
  first time. (See the bug cross reference earlier in this thread for a link
  to cage.)

So as far as I'm concerned, anything older than 6 months is automatically
moot.

**Comment by compressed** [comment]
Great thanks for the comments. I agree; I think `0.6.0` is a reasonable version to base our support around.

I've added a few commits to introduce the feature flags. I wasn't aware that struct field-level `#[cfg..]` were stable, but maybe they always were. Anyways, that made it easy to just keep one version of `VaultResponse` and pick which functions apply for newer vault versions.

The general idea is this: for features added in new vault versions we can add `#[cfg(feature = "vault_0.x.y")]` to that code. The `default` feature needs to include all vault version specific features, so that by default, the library targets the latest vault version. Users on older versions of vault will need to specify `default-features = false` in their `Cargo.toml` and pick which features apply to their version.

Travis seems happy now as well. I made a few changes to `.travis.yml` to get this to work. I don't think `travis-cargo` supports what we need from what I read, so I just used the raw commands instead.

**Comment by ChrisMacNaughton** [comment]
:+1: LGTM Thanks @compressed for this great work and thanks @emk for the feedback

**Pull request merged**
